# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
Dotenv.load('../.env') # 상대경로로 루트의 .env 불러오기

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    UI.message("🔑 KEY ID: #{ENV['APP_STORE_KEY_ID']}")
    UI.message("📄 PATH: #{ENV['APP_STORE_API_KEY_PATH']}")

    build_app(
      workspace: "Happiary.xcworkspace", 
      scheme: "Happiary",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "io.tuist.Happiary" => "match AppStore io.tuist.Happiary"
        },
        teamID: "72B557RJ7S"
      }
    )

    upload_to_testflight(
       api_key: app_store_connect_api_key(
         key_id: ENV["APP_STORE_KEY_ID"],
         issuer_id: ENV["APP_STORE_ISSUER_ID"],
         key_filepath: ENV["APP_STORE_API_KEY_PATH"]
       )
    )
  end
end
